/**
 * reporter.js - Generates markdown and JSON reports from audit results
 */

function getLeadTemperature(percentage) {
  if (percentage < 30) return '🔥🔥🔥 HOT LEAD';
  if (percentage < 50) return '🔥🔥 Warm Lead';
  if (percentage < 65) return '🔥 Lukewarm';
  if (percentage < 80) return '🌤️ Decent';
  return '✅ Well Built';
}

function getGradeEmoji(grade) {
  const map = { A: '🏆', B: '👍', C: '⚠️', D: '❌', F: '💀' };
  return map[grade] || '❓';
}

function formatCheckRow(key, check, meta) {
  const info = meta[key];
  const status = check.pass ? '✅' : '❌';
  return `| ${info.emoji} ${info.label} | ${status} | ${check.score}/${check.max} | ${check.detail} |`;
}

function generateBusinessSection(business, index) {
  const { name, website, city, phone, result, leadProfile = {} } = business;
  const rank = index + 1;
  
  if (!website || result.error) {
    return `
## #${rank} — ${name}
**No Website / Unreachable** ${result.error ? `(${result.error})` : ''}
- 📍 ${city || 'Unknown location'}
${phone ? `- 📞 ${phone}` : ''}
${leadProfile.publicEmail ? `- 📧 ${leadProfile.publicEmail}` : ''}
${leadProfile.outreachScore ? `- 🎯 Outreach Worthiness: ${leadProfile.outreachScore}/100 (${leadProfile.outreachTier})` : ''}
> **This is a PERFECT lead** — they have no web presence at all!

---`;
  }

  const temp = getLeadTemperature(result.percentage);
  const gradeEmoji = getGradeEmoji(result.grade);

  const checkRows = Object.entries(result.checks)
    .map(([key, check]) => formatCheckRow(key, check, result.checkMeta))
    .join('\n');

  const failedList = result.failedChecks.length > 0
    ? result.failedChecks.map(f => `- ❌ ${f}`).join('\n')
    : '- None! Site is well-optimized';

  return `
## #${rank} — ${name}
**${temp}** | Grade: ${gradeEmoji} ${result.grade} | Score: **${result.percentage}/100**

- 🌐 ${website}
${city ? `- 📍 ${city}` : ''}
${phone ? `- 📞 ${phone}` : ''}
${leadProfile.publicEmail ? `- 📧 ${leadProfile.publicEmail}` : ''}
${leadProfile.outreachScore ? `- 🎯 Outreach Worthiness: ${leadProfile.outreachScore}/100 (${leadProfile.outreachTier})` : ''}

### Audit Results
| Check | Pass? | Score | Detail |
|-------|-------|-------|--------|
${checkRows}

${leadProfile.priorityReasons?.length ? `### Why This Is Worth Outreach
${leadProfile.priorityReasons.map(reason => `- ${reason}`).join('\n')}

` : ''}
### Issues to Fix (Your Sales Pitch)
${failedList}

---`;
}

function generateMarkdownReport(businesses, meta) {
  const { city, category, auditDate, totalFound } = meta;
  
  const withSites = businesses.filter(b => b.website && !b.result.error);
  const withoutSites = businesses.filter(b => !b.website || b.result.error);
  const avgScore = withSites.length > 0
    ? Math.round(withSites.reduce((s, b) => s + b.result.percentage, 0) / withSites.length)
    : 0;

  const header = `# 📊 Local Business Website Audit Report
## ${category} in ${city}

**Audit Date:** ${auditDate}  
**Businesses Audited:** ${businesses.length} of ${totalFound} found  
**Businesses With Websites:** ${withSites.length}  
**Businesses Without Websites:** ${withoutSites.length} ← instant leads!  
**Average Website Score:** ${avgScore}/100  

> **How to read this:** Businesses are ranked **worst first** — these are your hottest leads.
> A score under 50 means their website is hurting them. You can help.

---
`;

  const sections = businesses.map((b, i) => generateBusinessSection(b, i)).join('\n');

  const footer = `
## 💡 Summary & Pitch Tips

${withoutSites.length > 0 ? `### Businesses With No Website (${withoutSites.length})
These are your easiest pitches. They have zero web presence.
${withoutSites.map(b => `- **${b.name}** ${b.phone ? `(${b.phone})` : ''}`).join('\n')}
` : ''}

### Common Issues Found
${generateCommonIssues(withSites)}

### Script Suggestion
> "Hi, I'm Gabriel — I help local businesses in ${city} get found online. I ran a quick audit on your website and found a few things that might be costing you customers. Mind if I share what I found?"

---
*Generated by Koa's Site Auditor — built for Gabriel's web dev business*`;

  return header + sections + footer;
}

function generateCommonIssues(businesses) {
  if (businesses.length === 0) return '- No websites to analyze';
  
  const issueCounts = {};
  businesses.forEach(b => {
    (b.result.failedChecks || []).forEach(issue => {
      issueCounts[issue] = (issueCounts[issue] || 0) + 1;
    });
  });

  const sorted = Object.entries(issueCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8);

  if (sorted.length === 0) return '- No major issues found';

  return sorted.map(([issue, count]) => {
    const pct = Math.round((count / businesses.length) * 100);
    return `- **${issue}** — ${count}/${businesses.length} businesses (${pct}%)`;
  }).join('\n');
}

function generateJSONReport(businesses, meta) {
  return {
    meta: {
      ...meta,
      generatedBy: 'site-auditor',
      version: '1.1.0'
    },
    summary: {
      totalFound: meta.totalFound,
      audited: businesses.length,
      withWebsites: businesses.filter(b => b.website && !b.result.error).length,
      withoutWebsites: businesses.filter(b => !b.website || b.result.error).length,
      averageScore: businesses.filter(b => b.result.percentage > 0).length > 0
        ? Math.round(businesses.filter(b => b.result.percentage > 0)
            .reduce((s, b) => s + b.result.percentage, 0) /
            businesses.filter(b => b.result.percentage > 0).length)
        : 0
    },
    businesses: businesses.map(b => ({
      rank: b.rank,
      name: b.name,
      website: b.website,
      phone: b.phone,
      city: b.city,
      leadTemperature: b.website && !b.result.error ? getLeadTemperature(b.result.percentage) : '🔥🔥🔥 HOT LEAD (no site)',
      score: b.result.percentage,
      grade: b.result.grade,
      error: b.result.error || null,
      publicEmail: b.leadProfile?.publicEmail || null,
      publicEmails: b.leadProfile?.publicEmails || [],
      outreachScore: b.leadProfile?.outreachScore || 0,
      outreachTier: b.leadProfile?.outreachTier || 'skip',
      shouldPursue: !!b.leadProfile?.shouldPursue,
      recommendedPackage: b.leadProfile?.recommendedPackage || null,
      estimatedValue: b.leadProfile?.estimatedValue || null,
      priorityReasons: b.leadProfile?.priorityReasons || [],
      cautions: b.leadProfile?.cautions || [],
      nextAction: b.leadProfile?.nextAction || null,
      quickPitch: b.leadProfile?.quickPitch || null,
      platform: b.leadProfile?.platform || null,
      checks: b.result.checks ? Object.fromEntries(
        Object.entries(b.result.checks).map(([k, v]) => [k, {
          pass: v.pass,
          score: v.score,
          max: v.max,
          detail: v.detail
        }])
      ) : {},
      failedChecks: b.result.failedChecks || [],
      loadTimeMs: b.loadTimeMs || null,
      leadProfile: b.leadProfile || null
    }))
  };
}

module.exports = { generateMarkdownReport, generateJSONReport, getLeadTemperature };
